[package]
name = "teki"
version = "0.1.0"
description = "Touhou-style shoot'em up"
authors = ["o2sh <ossama-hjaji@live.fr>"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/o2sh/teki"


[dependencies]
clap = "2.33.3"
specs = { version = "0.16.1", features = ["specs-derive"] }
rand = "0.8.0"

[dependencies.sdl2]
version = "0.34.3"
default-features = false
features = ["image"]